### ISSUE TITLE
I keep getting this error on linux

### ISSUE THREAD

**Issue by jerlegoman** [JonGabilondoAngulo/idevicelocation#1]
I keep on getting this error when compiling on both debian linux and ubuntu mate. I get it when i try to execute ./autogen.sh

Error:
./configure: line 13004: syntax error near unexpected token `GLOBAL_CFLAGS,'

./configure: line 13004: `AS_COMPILER_FLAGS(GLOBAL_CFLAGS, "-Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith  -Wwrite-strings -Wswitch-default -Wno-unused-parameter -Werror -g")'

Thanks!

**Comment by JonGabilondoAngulo** [comment]
I tested it only on Mac so far ...

**Comment by jerlegoman** [comment]
Ok I figured out a fix there was a missing file I will post the file and more info later when I get the chance

**Comment by ewscripps-jb** [comment]
I am getting similar error on macOS 10.13.3:

./configure: line 12976: syntax error near unexpected token `GLOBAL_CFLAGS,'
./configure: line 12976: `AS_COMPILER_FLAGS(GLOBAL_CFLAGS, "-Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith  -Wwrite-strings -Wswitch-default -Wno-unused-parameter -Werror -g")'

**Comment by bhanuneeli** [comment]
Hi, any update on this issue. Thanks.

**Comment by jerlegoman** [comment]
Im pretty sure this issue was fixed already in a previous commit. Make sure you downloaded the most recent version

**Comment by bhanuneeli** [comment]
Thank you for your reply. Now that I idevicelocation is setup on my Mac. When I try to do something like idevicelocation 48.856614 2.3522219000000177......  I am getting following error - "Could not connect to lockdownd. Exiting."

**Comment by JonGabilondoAngulo** [comment]
That is because  libimobiledevice is not the latest version, older versions have a problem with ios11. 
Check how to update libimobiledevice with brew to the HEAD version.

**Comment by bhanuneeli** [comment]
Hi JonGabilondoAngulo,

Thank you very much for your reply. I have updated the libimobiledevice version as advised. I am getting below error when I try to set the location on the real iOS device (iOS 11). The code snippet is below (using appium):

Location loc = new Location(40.712775, -74.005973, 13.0);
            driver.setLocation(loc);
**Error**:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Can't set the location on device '006ed12db46495ad350f3f988fa58a67832cfe38'. Original error: Command 'idevicelocation -u 006ed12db46495ad350f3f988fa58a67832cfe38 40.712775 -74.005973' exited with code 2 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 40 milliseconds

**Comment by JonGabilondoAngulo** [comment]
There is an exit(2) if the udid is wrong. (-u).
Execute in Terminal, using the command line you will get more information. Without Appium.
