### ISSUE TITLE
What if both the lat and lng are negative?

### ISSUE THREAD

**Issue by kiddyfurby** [JonGabilondoAngulo/idevicelocation#10]
idevicelocation -u xxxxxx -- -33.1314 -- -112.0213
This does not seem to work

**Comment by JonGabilondoAngulo** [comment]
Hi,
this would be the way in that case:

idevicelocation -u xxxxxx -- -33.1314  -112.0213

**Comment by kiddyfurby** [comment]
Awesome! thank you for the great tool!
