### ISSUE TITLE
Pull coordinates? :]

### ISSUE THREAD

**Issue by dnsBlah** [JonGabilondoAngulo/idevicelocation#12]
Is there any way to pull the coordinates of a device?

**Comment by JonGabilondoAngulo** [comment]
Interesting, do u know any external application that gets the location from the iPhone? That may help.

**Comment by dnsBlah** [comment]
I wish, I hoped this could be pulled from the mobilegestault?
Im now using a web api to push the device's coordinates to, and pull it.
