### ISSUE TITLE
Can't set the location on device

### ISSUE THREAD

**Issue by dron4ik86** [JonGabilondoAngulo/idevicelocation#14]
I try to set location on a real device but I get an error message:
`selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Can't set the location on device '14f9e52e7fc70b46d723c********'. Original error: Command 'idevicelocation -u 14f9e52e7fc70b46d723c******** 32.367327 34.9129022' exited with code null`
On Android it's works perfet for me
Appium version: 1.10.1
OS: MACOS 
Xcode version: 10.1

via terminal:
`$ idevicelocation -u 14f9e52e7fc70b46d723c28********* 32.36732761840638 34.912902299649886`

get Abort trap: 6

**Comment by JonGabilondoAngulo** [comment]
Hi,
I'm confused when you say it works on Android. This is a tool for iOS devices only.
It requires libimobiledevice installed. The iDevice must have the developer image installed. 
First check that ideviceifo, idevicename work ..
Try to build idevicelocation yourself following the instructions.
Cheers.

**Comment by dron4ik86** [comment]
> Hi,
> I'm confused when you say it works on Android. This is a tool for iOS devices only.
> It requires libimobiledevice installed. The iDevice must have the developer image installed.
> First check that ideviceifo, idevicename work ..
> Try to build idevicelocation yourself following the instructions.
> Cheers.

Hi,
Thank you for your answer.
I work with iOS, I wrote you that it's work on Android for example.
I work with iPhone 5s
