### ISSUE TITLE
No longer working as of iOS 12.2?

### ISSUE THREAD

**Issue by matt-monkfish** [JonGabilondoAngulo/idevicelocation#17]
I just updated my iPhone 7 to iOS 12.2, and idevicelocation no longer works on it. It was working fine previously, and still working with a 12.1.4 iPhone X that I just checked.

Are others seeing the same thing?

**Comment by JonGabilondoAngulo** [comment]
Hi,
tried in ios12.2 iPhone 6. I get a location change.
Does the problem persist in your case ?
Thanks.

**Comment by dnsBlah** [comment]
You'll have to update your xCode first
It works fine on my iPhoneX with iOS12.2

**Comment by matt-monkfish** [comment]
Per the previous comment, the problem was that I had not built to device with Xcode 10.2 after updating the phone to iOS 12.2. 

We are using the idevicelocation wrapped in a script, which suppressed the error message, which was the same as described in this issue: https://github.com/JonGabilondoAngulo/idevicelocation/issues/6
