### ISSUE TITLE
configure: error: Package requirements (libimobiledevice-1.0 >= 1.2.0) were not met:  Package 'openssl', required by 'libimobiledevice-1.0', not found

### ISSUE THREAD

**Issue by lafayea** [JonGabilondoAngulo/idevicelocation#18]
when I installed idevicelocation, I got this:
configure: error: Package requirements (libimobiledevice-1.0 >= 1.2.0) were not met: Package 'openssl', required by 'libimobiledevice-1.0', not found

then I tried to install libimobiledevice-1.2.0, it tells:
checking consistency of all components of python development environment... yes
checking for openssl... no
configure: error: OpenSSL support explicitly requested but OpenSSL could not be found

but I had already installed openssl :
wangdarens-MacBook-Pro:libimobiledevice-1.2.0 2 greatman$ brew upgrade openssl
Error: openssl 1.0.2r already installed

then I tried to use gnutls instead of openssl, it tells:
idevice.c:629:172: error: unknown type name 'gnutls_retr_st'; did you mean
      'gnutls_retr2_st'?
  ...* sign_algos, int sign_algos_length, gnutls_retr_st * st)
                                          ^~~~~~~~~~~~~~
                                          gnutls_retr2_st
/usr/local/Cellar/gnutls/3.6.7.1/include/gnutls/gnutls.h:2613:3: note: 
      'gnutls_retr2_st' declared here
} gnutls_retr2_st;
  ^
idevice.c:637:8: error: no member named 'type' in 'struct gnutls_retr2_st'
                        st->type = type;
                        ~~  ^
idevice.c:746:2: warning: implicit declaration of function
      'gnutls_certificate_client_set_retrieve_function' is invalid in C99
      [-Wimplicit-function-declaration]
        gnutls_certificate_client_set_retrieve_function(ssl_data_loc->ce...
        ^
1 warning and 2 errors generated.
make[2]: *** [idevice.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

what's wrong?

system version:
macOS Mojave 10.14.3

**Comment by jsveron23** [comment]
```
export PATH="/usr/local/opt/openssl/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/opt/openssl/lib:$LD_LIBRARY_PATH"
export CPATH="/usr/local/opt/openssl/include:$CPATH"
export LIBRARY_PATH="/usr/local/opt/openssl/lib:$LIBRARY_PATH"
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
```

**Comment by jsveron23** [comment]
you can install with source, I've fixed this way,

https://tonyj.in/get-started-with-appium/

**Comment by wendellou** [comment]
`brew update
brew uninstall --ignore-dependencies libimobiledevice 
brew uninstall --ignore-dependencies usbmuxd 
brew install --HEAD usbmuxd 
brew unlink usbmuxd 
brew link usbmuxd 
brew install --HEAD libimobiledevice

git clone https://github.com/JonGabilondoAngulo/idevicelocation.git

./autogen.sh
make
sudo make install`

I hope this code can help you. 😀

**Comment by jnguyen19** [comment]
Everything is fine, until the 2nd last step:(

./autogen.sh ran successfully after hours of get all the flags set and proper dependencies resolved.

 make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
  CC       idevicelocation-idevicelocation.o
clang: error: /usr/local/Cellar/libplist/2.2.0/bin: 'linker' input unused [-Werror,-Wunused-command-line-argument]
make[2]: *** [idevicelocation-idevicelocation.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
