### ISSUE TITLE
Could not start com.apple.dt.simulation

### ISSUE THREAD

**Issue by ICBMICBM** [JonGabilondoAngulo/idevicelocation#19]
The ideviceinfo is working correctly.
However when i tried the command 
'''
idevicelocation 0 0
'''
It returns could not start com.apple.dt.simulatelocation.

os:macos 10.14.4

**Comment by JonGabilondoAngulo** [comment]
Hi,
The developer image must be mounted.
If you have Xcode it will install it automatically.
