### ISSUE TITLE
Issues setting location from linux

### ISSUE THREAD

**Issue by jerlegoman** [JonGabilondoAngulo/idevicelocation#2]
When i try to set a location i get this:

GnuTLS error: Error in the pull function.
Could not connect to lockdownd. Exiting.

Thanks!

**Comment by JonGabilondoAngulo** [comment]
are u on iOS 11 ?
Does "ideviceinfo" work ?
There is a brand new fix for iOS 11 in https://github.com/libimobiledevice/libimobiledevice/issues/510
