### ISSUE TITLE
Does this tool work with devices connected over WiFi?

### ISSUE THREAD

**Issue by maksim-sushkevich** [JonGabilondoAngulo/idevicelocation#21]
Hi there!

This is the great tool, but I wounding to know if is there any way to pass mock GPS location to devices connected over WiFi?

I have found:
instruments sees devices connected over WiFi
idevice_id -l - does not see any devices
idevicesyslog - works over WiFi

It would be nice to get any help.
Thank you!

**Comment by AlexShimmy** [comment]
I have the same question

**Comment by AlexShimmy** [comment]
idevice_id overw works WiFi with -n (--network):

idevice_id -l -n

**Comment by maksim-sushkevich** [comment]
I have found a solution.
You can try out the solution here: https://github.com/maksim-sushkevich/idevicelocation

**Comment by JonGabilondoAngulo** [comment]
> idevice_id works over WiFi with -n (--network):
> 
> idevice_id -l -n
Hi,
I'm on Catalina, with device and computer on the same access point, 
idevice_id -l -n  doesn't return any device.
connected to USB I do see the device.

Is there anything I'm missing ?
thanks
