### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by BernhardFuchs** [JonGabilondoAngulo/idevicelocation#4]
I try to compile this on MacOS High Sierra 10.13.2 and already went past the `as-compiler-flag.m4` issue. That means `autogen.sh` finishes successfully.

When I run make I get the following error:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
  CC       idevicelocation-idevicelocation.o  
  CCLD     idevicelocation  
Undefined symbols for architecture x86_64:  
  "_idevice_free", referenced from:  
      _main in idevicelocation-idevicelocation.o  
  "_idevice_new", referenced from:  
      _main in idevicelocation-idevicelocation.o
  "_idevice_set_debug_level", referenced from:
      _main in idevicelocation-idevicelocation.o
  "_lockdownd_client_free", referenced from:
      _main in idevicelocation-idevicelocation.o
  "_lockdownd_client_new_with_handshake", referenced from:
      _main in idevicelocation-idevicelocation.o
  "_lockdownd_service_descriptor_free", referenced from:
      _main in idevicelocation-idevicelocation.o
  "_lockdownd_start_service", referenced from:
      _main in idevicelocation-idevicelocation.o
  "_service_client_free", referenced from:
      _main in idevicelocation-idevicelocation.o
  "_service_client_new", referenced from:
      _main in idevicelocation-idevicelocation.o
  "_service_send", referenced from:
      _main in idevicelocation-idevicelocation.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [idevicelocation] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I installed and use the latest gcc-7 compiler but that only changes `clang: error: linker command failed with exit code 1 (use -v to see invocation)` to `collect2: error: ld returned 1 exit status`.

I'm stuck with this at the moment.

**Comment by JonGabilondoAngulo** [comment]
Hi,
I upgraded to High Sierra 10.13.2.
I've done all the brew updates and upgrades.
Before autogen.sh I've set the environment variables defined in the troubleshooting section.
'make' is successful.
Let me know if your problems persist.

**Comment by xpertode** [comment]
@BernhardFuchs I was facing the similar issues. I tried following:
1. Check where libimobiledevice libraries are installed. For me they were at /usr/local/lib
2. Add the path to LIBRARY_PATH and LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
Check if this works for you :)

**Comment by BernhardFuchs** [comment]
Thanks @xpertode that was the correct hint. We solved it a bit differently by adding an option to the gcc command like this:  
`gcc -L/usr/local/lib -limobiledevice -o src/idevicelocation src/idevicelocation-idevicelocation.o`
