### ISSUE TITLE
Unexplained error when running idevicelocation

### ISSUE THREAD

**Issue by ericsavoiewaltz** [JonGabilondoAngulo/idevicelocation#6]
Description: I've been spoofing my location on a real device all day. About 20 minutes ago I started receiving this error: "Could not start com.apple.dt.simulatelocation!"

Right before I started receiving this error I restarted my device. I did not stop idevicelocation before restarting my device. I'm wondering if this caused an issue? 

Any help would be great. 
Thanks.

**Comment by ericsavoiewaltz** [comment]
I’m guessing this started because I restarted the phone without stopping
the simulation. But I’m not sure.

**Comment by dnsBlah** [comment]
I've had same issue here.
When I opened xCode and build an iOS app ( I just build without testing if opening was enough ) the library worked.

Is there any way we can use this library natively ?without xCode.
I'm using `export DYLD_LIBRARY_PATH=<path to libraries>:$DYLD_LIBRARY_PATH; PATH=${PATH}:<path to libraries>; <path to libraries>/idevicelocation`

**Comment by Fidetro** [comment]
@JonGabilondoAngulo Is there any way to not install Xcode but use it？Thank you for your time.

**Comment by dnsBlah** [comment]
Try to use ideviceimagemounter
You will need the applicable DeveloperImage from xCode for the iOS you are running tho ;)
